# Generated by Django 2.1.5 on 2019-10-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('room_rent', models.IntegerField()),
                ('mess_facility', models.BooleanField()),
                ('gender', models.BooleanField()),
            ],
        ),
    ]
