# Generated by Django 2.1.11 on 2019-10-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('room_rent', models.IntegerField()),
                ('mess_facility', models.BooleanField()),
                ('gender', models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], default='B', max_length=1)),
                ('distance_from_college', models.DecimalField(decimal_places=2, max_digits=8)),
                ('one_person', models.BooleanField()),
                ('two_person', models.BooleanField()),
                ('three_person', models.BooleanField()),
            ],
        ),
    ]
