# Generated by Django 2.1.11 on 2019-10-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGlisting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='gender',
            field=models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], default='B', max_length=1),
        ),
    ]
